---
# Install dependencies for docker-ce

- name: Install dependencies needed for docker-ce on host.
  yum:
    name:
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add CentOS docker-ce repo.
  yum_repository:
    name: docker-ce-stable
    description: docker-ce stable repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: true
  when: ansible_distribution == 'CentOS'

- name: Add Fedora docker-ce repo.
  yum_repository:
    name: docker-ce-stable
    description: docker-ce stable repo
    baseurl: >
      https://download.docker.com/linux/fedora/28/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
    enabled: true
  changed_when: false
  when: ansible_distribution != 'CentOS'

- name: Install docker-ce on host.
  package:
    name: docker-ce
