---
# tasks file for ansible-docker-role

- name: Set ansible_user if undefined.
  set_fact: ansible_user="root"
  when: ansible_user is undefined

- include: installdeps-centos.yml
  when: ansible_os_family == 'RedHat'

- include: installdeps-ubuntu.yml
  when: ansible_os_family == 'Debian'

- include: docker.yml
